### ISSUE TITLE
java.net.ConnectException with two modules

### ISSUE THREAD

**Issue by loic-seguin** [jcabi/jcabi-dynamodb-maven-plugin#63]
Hi,

I tried your plugin following this page http://dynamodb.jcabi.com/usage.html.
I used the three goals 'start', 'create-tables' and 'stop'.

It works well with one module.

But when we have two modules, if we run 'mvn clean verify' in each module everything goes well but if we run this command at the pom parent level, we get a java.net.ConnectException at the 'create-tables' goal for the second module which is compiled by maven.

Here is a really simple project with no code at all 
[example-project-two-modules.zip](https://github.com/jcabi/jcabi-dynamodb-maven-plugin/files/790010/example-project-two-modules.zip)

(You can try it if you want)

There are only a pom parent, two modules with their own pom and that's it.

If I run the command 'mvn clean verify' in moduleA or in moduleB, everything is ok.

If I run the command at the pom parent level, module A is processed by maven without any problem. The goals 'start', 'create-tables' and 'stop' are done well. When module B is processed by maven we got multiple times java.net.ConnectException during the goal 'create-tables' until the connection works.

I directly though of aws problem regarding the logs below :

at com.amazonaws.services.dynamodbv2.util.TableUtils.waitUntilExists(TableUtils.java:100)
at com.jcabi.dynamodb.core.Tables.exists(Tables.java:160)

So I clone your project jcabi-dynamodb-maven-plugin and I upgrade these two dependencies aws-java-sdk-core and aws-java-sdk-dynamodb to 1.11.25. Under this version, we got the same exception.

I compiled it and used it instead of 0.8 version. And it worked.

Can I do a PR about this issue ?

Regards

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by slolo83510** [comment]
Please, can I have feedback concerning this issue ?

**Comment by loic-seguin** [comment]
Hi,

Could I have feedback concerning this issue ?

**Comment by yegor256** [comment]
@loic-seguin yes, please submit a pull request. Thanks!

**Comment by yegor256** [comment]
@rultor release tag is `0.9.1`

**Comment by yegor256** [comment]
@loic-seguin your PR #66 was merged, let me release a new version and ask you to try again
