### ISSUE TITLE
UnsatisfiedLinkError: no sqlite4java-linux-amd64-1.0.392 in java.library.path

### ISSUE THREAD

**Issue by vdzhuvinov** [jcabi/jcabi-dynamodb-maven-plugin#68]
Hi,
I would like to report an odd error. I setup pom.xml with the latest release. The plugin executes without any errors as configured, however, when trying to make a connection from within a test, an error complaining that an sqllite native .so cannot be found and loaded (on a Linux system) gets thrown:

```
SEVERE: [sqlite] SQLiteQueue[]: error running job queue
com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: no sqlite4java-linux-amd64-1.0.392 in java.library.path
        at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
        at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
        at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
        at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293)
        at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464)
        at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641)
        at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
        at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
        at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: no sqlite4java-linux-amd64-1.0.392 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.almworks.sqlite4java.Internal.tryLoadFromSystemPath(Internal.java:352)
        at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:124)
        at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
        ... 9 more
```

Shouldn't `java.library.path` be set somewhere?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@vdzhuvinov this is really weird. Can you share your pom.xml so that I can test it too?

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-dynamodb-maven-plugin#68` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by vdzhuvinov** [comment]
Sure, here it is: 

https://bitbucket.org/connect2id/dynamodb-cache-store/src/09f50e0328bdb76fdac63ecf08364b3d25dc2eaf/pom.xml?at=master&fileviewer=file-view-default

At present I start / stop the local DynamoDB manually.

**Comment by 0crat** [comment]
@yegor256 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:jcabi/jcabi-dynamodb-maven-plugin#68`, please stop working.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/jcabi/jcabi-dynamodb-maven-plugin/issues/68#issuecomment-386282635))

@yegor256 The job [#68](https://github.com/jcabi/jcabi-dynamodb-maven-plugin/issues/68) is now out of scope
